# Copyright (c) 2026 0x5BFA
# Licensed under the MIT License. See the LICENSE.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$ProjectPath,

    [string]$Platform = "x64",
    [string]$Configuration = "Debug",
    [bool]$IsStorePublish = $false,
    [string]$PackageManifestPath = "",
    [string]$PackageCertificateKeyFile = "",
    [string]$AppxBundlePlatforms = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3.0

if (-not [IO.File]::Exists([IO.Path]::GetFullPath($ProjectPath)))
{
    throw "The application project does not exist: $ProjectPath"
}

if ($IsStorePublish)
{
    if ([string]::IsNullOrWhiteSpace($PackageManifestPath) -or
        -not [IO.File]::Exists([IO.Path]::GetFullPath($PackageManifestPath)))
    {
        throw "The Store package manifest does not exist: $PackageManifestPath"
    }

    # Keep the Store identity from the checked-in manifest. The temporary signing
    # certificate generated by the workflow must match that Publisher value.
    [xml]$manifest = Get-Content -LiteralPath $PackageManifestPath -Raw
    $identity = $manifest.SelectSingleNode(
        "/*[local-name()='Package']/*[local-name()='Identity']"
    )

    if ($null -eq $identity -or
        [string]::IsNullOrWhiteSpace($identity.GetAttribute("Name")) -or
        [string]::IsNullOrWhiteSpace($identity.GetAttribute("Publisher")))
    {
        throw "The Store package manifest must contain an Identity Name and Publisher."
    }
}

$buildArguments = @(
    [IO.Path]::GetFullPath($ProjectPath),
    "-restore",
    "/clp:ErrorsOnly",
    "/p:Platform=$Platform",
    "/p:Configuration=$Configuration"
)

if ($IsStorePublish)
{
    $packageBuildMode = if ([string]::IsNullOrWhiteSpace($PackageCertificateKeyFile))
    {
        "StoreOnly"
    }
    else
    {
        "StoreUpload"
    }

    $buildArguments += "/p:UapAppxPackageBuildMode=$packageBuildMode"
    $buildArguments += @(
        "/p:GenerateAppxPackageOnBuild=true",
        "/p:AppxBundle=Always"
    )
}
else
{
    $buildArguments += "/p:AppxBundle=Never"
}

if (-not [string]::IsNullOrWhiteSpace($AppxBundlePlatforms))
{
    $buildArguments += "/p:AppxBundlePlatforms=$AppxBundlePlatforms"
}

if (-not [string]::IsNullOrWhiteSpace($PackageCertificateKeyFile))
{
    $certificatePath = [IO.Path]::GetFullPath($PackageCertificateKeyFile)

    if (-not [IO.File]::Exists($certificatePath))
    {
        throw "The package signing certificate does not exist: $certificatePath"
    }

    $buildArguments += @(
        "/p:AppxPackageSigningEnabled=true",
        "/p:PackageCertificateKeyFile=$certificatePath"
    )
}

& msbuild @buildArguments

if ($LASTEXITCODE -ne 0)
{
    throw "MSBuild failed with exit code $LASTEXITCODE."
}
