global using global::System;
global using global::System.Collections;
global using global::System.Collections.Generic;
global using global::System.Collections.ObjectModel;
global using global::System.ComponentModel;
global using global::System.Diagnostics;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::Microsoft.UI.Xaml;
global using global::Microsoft.UI.Xaml.Controls;
global using global::Microsoft.UI.Xaml.Controls.Primitives;
global using global::RegistryEditor.Controls.Primitives;
global using SystemIO = global::System.IO;
