<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>

		<!--  WinUI properties  -->
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>
		<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
		<ApplicationIcon>Assets\Branding\AppLogo.ico</ApplicationIcon>
		<DisableXbfLineInfo>false</DisableXbfLineInfo>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<!--  MSIX packaging properties  -->
		<EnableMsixTooling>true</EnableMsixTooling>
		<DefaultLanguage>en-US</DefaultLanguage>
		<AppxPackageSigningTimestampDigestAlgorithm>sha256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>true</AppxAutoIncrementPackageRevision>
		<AppxBundle Condition="'$(Configuration)' == 'Debug'">Never</AppxBundle>
		<AppxBundle Condition="'$(Configuration)' != 'Debug'">Always</AppxBundle>
		<AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
		<UapAppxPackageBuildMode>StoreAndSideload</UapAppxPackageBuildMode>
		<GenerateAppxPackageOnBuild Condition="'$(Configuration)' != 'Debug'">true</GenerateAppxPackageOnBuild>
		<AppxBundleAutoResourcePackageQualifiers>Scale|DXFeatureLevel</AppxBundleAutoResourcePackageQualifiers>
		<!--<AppxDefaultResourceQualifiers>Language=en-US;af;ar;be-BY;bg;ca;cs-CZ;da;de-DE;el;en-GB;es-ES;es-419;fa-IR;fi-FI;fil-PH;fr-FR;he-IL;hi-IN;hr-HR;hu-HU;hy-AM;id-ID;it-IT;ja-JP;ka;km-KH;ko-KR;lt-LT;lv-LV;ms-MY;nb-NO;nl-NL;pl-PL;pt-BR;pt-PT;ro-RO;ru-RU;sk-SK;sq-AL;sr-Cyrl;sv-SE;ta;th-TH;tr-TR;uk-UA;vi;zh-Hans;zh-Hant</AppxDefaultResourceQualifiers>-->

		<!--  Publish AOT  -->
		<PublishAot>true</PublishAot>
		<ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
		<IlcTreatWarningsAsErrors>false</IlcTreatWarningsAsErrors>
		<SelfContained>true</SelfContained>
		<IlcGenerateMstatFile>true</IlcGenerateMstatFile>
		<IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>
		
	</PropertyGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
		<Content Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.DependencyPropertyGenerator" Version="0.1.250206-build.2040" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" ExcludeAssets="all" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.260610101" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
	</ItemGroup>

</Project>
