# Copyright (c) 0x5BFA. All rights reserved.
# Licensed under the MIT license.

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'builds/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'builds/**'
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'PR Validation' || 'CI Validation' }}

env:
  WORKING_DIR:         '${{ github.workspace }}' # 'D:\a\RegistryEditor\RegistryEditor'
  WASDK_APP_PROJ_PATH: '${{ github.workspace }}\RegistryEditor.WinUI\RegistryEditor.WinUI.csproj'

jobs:
  build-wasdk:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v5

    - name: Build the solution
      run: msbuild /restore $env:WASDK_APP_PROJ_PATH /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM /p:AppxBundle=Never
